#!/bin/bash

prefix=/usr/local

echo "Installing patchomv utility..."

sudo cp patchomv "$prefix"/bin

mkdir -p "$prefix"/share/patchomv
sudo cp share-patchomv/* "$prefix"/share/patchomv

sudo cp 99patchomv /etc/apt/apt.conf.d

echo "Done."
