#!/bin/bash

patched="2:4.22.8"
data="/usr/share/patchomv"

function samba_fruit_nfsaces()
{
  local march=$(arch)

  cmp -s "$data/fruit.so" /usr/lib/${march}-linux-gnu/samba/vfs/fruit.so && change="no" || change="yes"
  if [ "$change" = "yes" ]; then
    current=$(dpkg-query -f '${Version}' -W samba | sed 's/+.*//')
    [ "$current" = "$patched" ] && recompile="no" || recompile="yes"
    if [ "$recompile" = "yes" ]; then
      echo "*** WARNING: fruit module must be recompiled for current samba version $current"
      return
    fi
    echo "Use fruit module with nfs_aces share support"
    sudo cp "$data/fruit.so" /usr/lib/${march}-linux-gnu/samba/vfs/fruit.so
    sudo systemctl restart smbd
  fi
}


# main

samba_fruit_nfsaces
