#!/bin/bash

# internal variables and functions, do not touch
PACKAGE="patchomv"
deploy="/srv/salt/omv/deploy"
apply_salt=no
restart_engined=no
category=
data="/usr/share/patchomv"
quiet="no"
rmall="no"

function log()
{
  [ "$quiet" = "yes" ] && return
  echo "* $1"
}

function set_env()
{
  (omv-env get $2 | grep -q "$3" ) && enabled=yes || enabled=no
  if [ "$rmall" = "yes" ]; then
    unset_env "$1" "$2"
    return
  fi
  if [ "$enabled" = "no" ]; then
    log "Set $2 to $3: "
    omv-env set $2 "$3"
    apply_salt=yes
    category="$category\n$1"
  fi
}

function unset_env()
{
  log "Unset $2: "
  omv-env unset $2
  apply_salt=yes
  category="$category\n$1"
}

function get_env()
{
  local val="$(sudo omv-env get "$1" | cut -d '=' -f2)"
  echo "${val:-$2}"
}

function file_changed ()
{
  src="$data/$1"
  dest="$deploy/$2"
  _retval=1
  if [ ! -e "$dest" ] || ! cmp -s "$src" "$dest"; then
    cp "$src" "$dest"
    _retval=0
  fi
  return $_retval
}

# this function must be called last
function finally_apply_all()
{
  category=$(echo -e $category | sort | uniq | tr "\n" " ")
  if [ "$apply_salt" = "yes" ]; then
    echo "Applying salt configuration"
    echo "   staging ..."
    sudo omv-salt stage run -q prepare
    echo "   deploying ..."
    sudo omv-salt deploy run -q $category
    echo "done."
  else
    echo "Nothing to apply."
  fi
  if [ "$restart_engined" = "yes" ]; then
    echo "Restarting omv-engined"
    sudo systemctl restart openmediavault-engined
  fi
}


# --- functions which modify js files

function apply_confirmation()
{
  if [ "$1" = "remove" ] || [ "$rmall" = "yes" ]; then
    file=$(grep -l 'showConfirmCheckbox=!1);break' /var/www/openmediavault/*js)
    if [ -n "$file" ]; then
      log "OMV default: Enable confirmation checkbox"
      sed -i -e 's|showConfirmCheckbox=!1);break|showConfirmCheckbox=!0,this.config.buttons\[1\].disabled=!0);break|' "$file" 
    fi
  else 
    file=$(grep -l 'showConfirmCheckbox=!0,this.config.buttons\[1\].disabled=!0' /var/www/openmediavault/*js)
    if [ -n "$file" ]; then
      log "Remove confirmation checkbox"
      sed -i -e 's|showConfirmCheckbox=!0,this.config.buttons\[1\].disabled=!0|showConfirmCheckbox=!1|' "$file"
    fi
  fi
}

function sharename_spaces()
{
  local change="no"
  if [ "$1" = "remove" ] || [ "$rmall" = "yes" ]; then
    file=$(grep -l ':+|<>=;,\*?\.]' /var/www/openmediavault/*js)
    if [ -n "$file" ]; then
      log "OMV default: forbid spaces in share names - 1"
      sed -i -e 's/:+|<>=;,\*?\.]/:+|<>=;,\*?\. ]/g' "$file"
    fi
    grep -q ':+|<>=;,\*?\.]' /usr/lib/python3/dist-packages/openmediavault/datamodel/schema.py && change="yes"
    if [ "$change" = "yes" ]; then
      log "OMV default: forbid spaces in share names - 2"
      cd /usr/lib/python3/dist-packages/openmediavault/datamodel
      patch -R -p0 < "$data/samba-spaces.diff"
      apply_salt="yes"
      category="$category\nsamba"
    fi
  else
    file=$(grep -l ':+|<>=;,\*?\. ]' /var/www/openmediavault/*js)
    if [ -n "$file" ]; then
      log "Allow spaces in share names - 1"
      sed -i -e 's/:+|<>=;,\*?\. ]/:+|<>=;,\*?\.]/g' "$file"
    fi
    grep -q ':+|<>=;,\*?\. ]' /usr/lib/python3/dist-packages/openmediavault/datamodel/schema.py && change="yes"
    if [ "$change" = "yes" ]; then
      log "Allow spaces in share names - 2"
      cd /usr/lib/python3/dist-packages/openmediavault/datamodel
      patch -p0 < "$data/samba-spaces.diff"
      apply_salt="yes"
      category="$category\nsamba"
    fi
  fi
}

function identifier_spaces()
{
  if [ "$1" = "remove" ] || [ "$rmall" = "yes" ]; then
    file=$(grep -l '/^\[\\w \]+\$/' /var/www/openmediavault/*js)
    if [ -n "$file" ]; then
      log "OMV default: forbid spaces in identifiers"
      sed -i -e 's|\^\[\\w\ ]+\$|\^\[\\w\]+\$|' "$file"
    fi
  else
    file=$(grep -l '/^\[\\w\]+\$/' /var/www/openmediavault/*js)
    if [ -n "$file" ]; then
      log "Allow spaces in identifiers"
      sed -i -e 's|\^\[\\w\]+\$|\^\[\\w \]+\$|' "$file"
    fi
  fi
}

function optional_domainname ()
{
  if [ "$1" = "remove" ] || [ "$rmall" = "yes" ]; then
    file=$(grep -l 'domainName",required:!1' /var/www/openmediavault/*js)
    if [ -n "$file" ]; then
      log "OMV default: domainname required"
      sed -i -e 's/domainName",required:!1/domainName",required:!0/' "$file"
    fi
  else
    file=$(grep -l 'domainName",required:!0' /var/www/openmediavault/*js)
    if [ -n "$file" ]; then
      log "Domainname optional"
      sed -i -e 's/domainName",required:!0/domainName",required:!1/' "$file"
    fi
  fi
}

function si_units()
{
  if [ "$1" = "remove" ] || [ "$rmall" = "yes" ]; then
    file=$(grep -l ">1000.*/=1000" /var/www/openmediavault/*js)
    if [ -n "$file" ]; then
      log "OMV default: Use IEC units (1024) instead of SI (1000)"
      sed -i -e 's|KB","MB","GB","TB","PB","EB","ZB","YB|KiB","MiB","GiB","TiB","PiB","EiB","ZiB","YiB|' "$file"
      sed -i -e "s|>1000\(.*\)/=1000|>1024\1/=1024|" "$file"
    fi
  else
    file=$(grep -l ">1024.*/=1024" /var/www/openmediavault/*js)
    if [ -n "$file" ]; then
      log "Use SI units (1000) instead of IEC (1024)"
      sed -i -e 's|KiB","MiB","GiB","TiB","PiB","EiB","ZiB","YiB|KB","MB","GB","TB","PB","EB","ZB","YB|' "$file"
      sed -i -e "s|>1024\(.*\)/=1024|>1000\1/=1000|" "$file"
    fi
  fi
}

# diff patches

function hostname_case()
{
  local change="no"
  if [ "$1" = "remove" ] || [ "$rmall" = "yes" ]; then
    grep -q "lower" /srv/salt/omv/deploy/hostname/default.sls || change=yes
    if [ "$change" = "yes" ]; then
      log "OMV default: hostname always lower case"
      cd /srv/salt/omv/deploy/hostname
      patch -R -p0 < "$data/hostname-default.sls.diff"
      apply_salt=yes
      category="$category\nhostname\navahi"
    fi
  else
    grep -q "lower" /srv/salt/omv/deploy/hostname/default.sls && change=yes
    if [ "$change" = "yes" ]; then
      log "Hostname case sensitive"
      cd /srv/salt/omv/deploy/hostname
      patch -p0 < "$data/hostname-default.sls.diff"
      apply_salt=yes
      category="$category\nhostname\navahi"
    fi
  fi
}

function show_users_group()
{
  local change="no"
  if [ "$1" = "remove" ] || [ "$rmall" = "yes" ]; then
    grep -q 'name == "users"' /usr/share/php/openmediavault/system/group.inc && change="yes"
    if [ "$change" = "yes" ]; then
      log "OMV default: hide modification of group users"
      cd /usr/share/php/openmediavault/system
      patch -R -p0 < "$data/group.inc.diff"
      restart_engined="yes"
    fi
  else
    grep -q 'name == "users"' /usr/share/php/openmediavault/system/group.inc || change="yes"
    if [ "$change" = "yes" ]; then
      log "Allow modification of group users"
      cd /usr/share/php/openmediavault/system
      patch -p0 < "$data/group.inc.diff"
      restart_engined="yes"
    fi
  fi
}

function compose_link_bonjour()
{
  [ -e /usr/share/openmediavault/engined/rpc/compose.inc ] || return
  local change="no"
  if [ "$1" = "remove" ] || [ "$rmall" = "yes" ]; then
    grep -q "if (empty(.dn))" /usr/share/openmediavault/engined/rpc/compose.inc && change="yes"
    if [ "$change" = "yes" ]; then
      log "OMV-Default: Forbid Compose CTerm links for .local domain"
      cd /usr/share/openmediavault/engined/rpc
      patch -R -p0 < "$data/compose.inc.diff"
      restart_engined="yes"
    fi
  else
    grep -q "if (empty(.dn))" /usr/share/openmediavault/engined/rpc/compose.inc || change="yes"
    if [ "$change" = "yes" ]; then
      log "Compose CTerm links for .local domain"
      cd /usr/share/openmediavault/engined/rpc
      patch -p0 < "$data/compose.inc.diff"
      restart_engined="yes"
    fi
  fi
}


# --- functions which don't modify source and are still there after updates

function samba_global_mac()
{
  local change=no
  local msg
  if [ "$1" = "remove" ] || [ "$rmall" = "yes" ]; then
    # remove patch
    rm "$deploy/samba/11global.sls" 2> /dev/null && change="yes"
    rm -f "$deploy/samba/files/global-mac.j2" 2> /dev/null && change="yes"
    msg="Removing macOS optimizations from samba"
  else
    file_changed 11global.sls samba/11global.sls && change="yes"
    file_changed global-mac.j2 samba/files/global-mac.j2 && change="yes"
    msg="Optimize samba for macOS"
  fi
  if [ "$change" = "yes" ]; then
    log "$msg"
    apply_salt="yes"
    category="$category\nsamba"
  fi 
}


function enable_hdparm()
{
  local change=no
  local msg

  if [ "$1" = "remove" ] || [ "$rmall" = "yes" ]; then
    rm "$deploy/smartmontools/22hdparm.sls" 2> /dev/null && change="yes"
    rm "$deploy/smartmontools/files/etc-hdparm.conf.j2" 2> /dev/null && change="yes"
    msg="OMV default: Removing hdparm and enable smartctl-hdparm"
  else
    file_changed 22hdparm.sls smartmontools/22hdparm.sls && change="yes"
    file_changed etc-hdparm.conf.j2 smartmontools/files/etc-hdparm.conf.j2 && change="yes"
    msg="Disable smartctl-hdparm and enable hdparm"
  fi
  if [ "$change" = "yes" ]; then
    log "$msg"
    if [ ! -e /usr/sbin/hdparm ]; then
      log "Installing hdparm package"
      sudo apt install -y hdparm
    fi
    sudo rm -f /etc/hdparm.conf
    apply_salt="yes"
    category="$category\nsmartmontools"
  fi

}


function cron_timer()
{
  local change="no"
  local msg
  if [ "$1" = "remove" ] || [ "$rmall" = "yes" ]; then
    local sysd=$(get_env OMV_SYSTEMD_DIR '/var/lib/openmediavault/systemd')
    local pfix=$(get_env OMV_SYSTEMD_TASK_PREFIX 'omv-task-')
    local scriptd="$(get_env OMV_CRONSCRIPTS_DIR '/var/lib/openmediavault/cron.d')"
    local scriptpfix="$(get_env OMV_CRONTAB_USERDEFINED_PREFIX 'userdefined-')"
    while read -r timer service; do
      systemctl stop "$timer" "$service"
      systemctl disable "$timer" "$service"
      change="yes"
    done < <(systemctl -a --no-pager list-timers | grep -oE "$pfix.*service")
    if [ "$change" = "yes" ]; then
      rm -f "$sysd/$pfix"*
      rm -f "$scriptd/$scriptpfix"*
      rm -f "$deploy/cron/30tasks-systemd.sls" "$deploy/cron/files/task_service.j2" "$deploy/cron/files/task_timer.j2"
      if [ -e "$deploy/cron/20userdefined.sls.distrib" ]; then
        dpkg-divert --package "$PACKAGE" --remove --rename "$deploy/cron/20userdefined.sls"
      fi
      msg="OMV default: Use cron instead of modern systemd timers"
    fi
  else
    file_changed 30tasks-systemd.sls cron/30tasks-systemd.sls && change="yes"
    file_changed task_service.j2 cron/files/task_service.j2 && change="yes"
    file_changed task_timer.j2 cron/files/task_timer.j2 && change="yes"
    if [ -e "$deploy/cron/20userdefined.sls" ]; then
      dpkg-divert --package "$PACKAGE" --add --rename --divert "$deploy/cron/20userdefined.sls.distrib" "$deploy/cron/20userdefined.sls"
      change="yes"
    fi
    [ "$change" = "yes" ] &&  msg="Use systemd timers for cron"
  fi
  if [ "$change" = "yes" ]; then
    log "$msg"
    apply_salt="yes"
    category="$category\ncron"
  fi
}


function rsync_timer()
{
  local change="no"
  local msg
  if [ "$1" = "xxx remove" ] || [ "$rmall" = "yes" ]; then
    local sysd=$(get_env OMV_SYSTEMD_DIR '/var/lib/openmediavault/systemd')
    local pfix=$(get_env OMV_SYSTEMD_RSYNC_PREFIX 'omv-rsync-')
    local scriptd="$(get_env OMV_CRONSCRIPTS_DIR '/var/lib/openmediavault/cron.d')"
    local scriptpfix="$(get_env OMV_RSYNC_CRONSCRIPT_PREFIX 'rsync-')"
    while read -r timer service; do
      systemctl stop "$timer" "$service"
      systemctl disable "$timer" "$service"
      change="yes"
    done < <(systemctl -a --no-pager list-timers | grep -oE "$pfix.*service")
    if [ "$change" = "yes" ]; then
      rm -f "$sysd/$pfix"*
      rm -f "$scriptd/$scriptpfix"*
      rm -f "$deploy/rsync/default.sls" "$deploy/rsync/files/rsync_service.j2" "$deploy/rsync/files/rsync_timer.j2"
      if [ -e "$deploy/rsync/default.sls.distrib" ]; then
        rm -f "$deploy/rsync/default.sls"
        dpkg-divert --package "$PACKAGE" --remove --rename "$deploy/rsync/default.sls"
      fi
      msg="OMV default: Use cron for rsync instead of modern systemd timers"
    fi
  else
    if [ ! -e "$deploy/rsync/default.sls.distrib" ]; then
      dpkg-divert --package "$PACKAGE" --add --rename --divert "$deploy/rsync/default.sls.distrib" "$deploy/rsync/default.sls"
    fi
    file_changed 30rsync-systemd.sls rsync/default.sls && change="yes"
    file_changed rsync_service.j2 rsync/files/rsync_service.j2 && change="yes"
    file_changed rsync_timer.j2 rsync/files/rsync_timer.j2 && change="yes"
    [ "$change" = "yes" ] && msg="Use systemd timers for rsync"
  fi
  if [ "$change" = "yes" ]; then
    log "$msg"
    apply_salt=yes
    category="$category\nrsync"
  fi
}


function avahi_no_count_hostname()
{
  local change="no"
  local msg
  if [ "$1" = "remove" ] || [ "$rmall" = "yes" ]; then
    rm -f "$deploy/avahi/files/etc-avahi-avahi-daemon_conf_no2.j2" # old patch version
    rm -f "$deploy/avahi/21configure.sls"
    msg="OMV default: remove avahi no -2 hostnames"
  else
    # rm old patch version
    rm -f "$deploy/avahi/files/etc-avahi-avahi-daemon_conf_no2.j2"
    file_changed 21configure.sls avahi/21configure.sls && change="yes"
    msg="Avahi no -2 hostnames"
  fi
  if [ "$change" = "yes" ] || [ "$_delete" = "yes" ]; then
    log "$msg"
    apply_salt="yes"
    category="$category\navahi"
  fi
}

function shares_symlinks()
{
  local change="no"
  local msg
  if [ "$1" = "remove" ] || [ "$rmall" = "yes" ]; then
    rm "$deploy/systemd/15sharelink.sls" 2> /dev/null && change="yes"
    rm /shares/*
    rmdir /shares 2> /dev/null
    msg="OMV default: no symlinks for shares"
  else
    file_changed 15sharelink.sls systemd/15sharelink.sls && change="yes"
    msg="Symlinks for shares"
  fi
  if [ "$change" = "yes" ]; then
    log "$msg"
    apply_salt="yes"
    category="$category\nsystemd"
  fi
}


# --- main
if [[ $EUID -ne 0 ]]; then
  echo "Error: This script must be run with sudo."
  exit 1
fi

while [ "$#" -gt 0 ] ; do
  case "$1" in
    -q) quiet="yes"
      ;;
    -rmall) rmall="yes"
      ;;
    *)
      ;;
  esac
  shift
done

echo "Looking for patches and configuration changes to OMV"

# omv environment variables
# to remove or unset a variable, change 'set_env' to 'unset_env', e.g: unset_env samba OMV_SAMBA_CREATEMASK 0644
# 
# ensure mac specific samba settings
set_env samba OMV_SAMBA_FRUIT_AAPL yes
set_env samba OMV_SAMBA_SHARE_VFSOBJECTS "fruit streams_xattr"
set_env samba OMV_SAMBA_HOMES_VFSOBJECTS "fruit streams_xattr"
# Mac style UNIX permissions, used when setting fruit:nfs_aces=no
set_env samba OMV_SAMBA_CREATEMASK 0644
set_env samba OMV_SAMBA_DIRECTORYMASK 0755
set_env samba OMV_SAMBA_HOMES_CREATEMASK 0644
set_env samba OMV_SAMBA_HOMES_DIRECTORYMASK 0755
set_env samba OMV_SAMBA_SHARE_CREATEMASK 0644
set_env samba OMV_SAMBA_SHARE_DIRECTORYMASK 0755
set_env samba OMV_SAMBA_SHARE_FORCECREATEMODE 0600
set_env samba OMV_SAMBA_SHARE_FORCEDIRECTORYMODE 0700
# Mac specific settings to act like macOS smb server
set_env samba OMV_SAMBA_SHARE_FRUIT_NFSACES yes
set_env samba OMV_SAMBA_SHARE_FRUIT_COPYFILE no
set_env samba OMV_SAMBA_SHARE_FRUIT_RESOURCE xattr

# modify settings using salt
# to remove a modification, add 'remove' as parameter to the function, e.g: enable_hdparm remove
avahi_no_count_hostname
enable_hdparm
samba_global_mac
cron_timer
rsync_timer
shares_symlinks

# modify source code
# to remove a modification, add 'remove' as parameter to the function, e.g: sharename_spaces remove
# modify .js
sharename_spaces
identifier_spaces
apply_confirmation
optional_domainname
si_units
# diff patches
hostname_case
show_users_group
compose_link_bonjour

# don't remove this line
finally_apply_all
