#!/bin/sh
set -e

. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    install|upgrade)
        omv="$(dpkg-query -f '${Version}' -W openmediavault)"
        if dpkg --compare-versions "$omv" ge "8.2.7-1"; then
            if omv-env get OMV_SAMBA_ZEROCONF_NAME | grep -q "%h" ; then
                omv-env unset OMV_RSYNC_ZEROCONF_NAME
                omv-env unset OMV_SSHD_ZEROCONF_NAME
                omv-env unset OMV_WEBGUI_ZEROCONF_NAME
                omv-env unset OMV_SAMBA_ZEROCONF_NAME
                omv_module_set_dirty avahi
            fi
        fi
        if dpkg --compare-versions "$omv" ge "8.5.8-1"; then
            vfsobj=$(omv-env get OMV_SAMBA_SHARE_VFSOBJECTS | cut -d'=' -f2)
            if [ "$vfsobj" = "fruit streams_xattr" ]; then 
                omv-env unset OMV_SAMBA_SHARE_VFSOBJECTS
                omv-env unset OMV_SAMBA_HOMES_VFSOBJECTS
                omv_module_set_dirty samba
            fi
        fi
        # remove divert of former version
        if dpkg-divert --list | grep -q "hdparm.conf" ; then
            dpkg-divert --local --remove --no-rename /etc/hdparm.conf
        fi 
esac

exit 0